import type { Metadata } from "next";

import "./globals.css";

import { quicksand } from "./utils/importedFonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className }  bg-selfPrimary overflow-x-hidden scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
